version: '3'

services:
  food-delivery-db:
    image: arm64v8/mysql
    privileged: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ead8686ba57479778a76e" 
      MYSQL_USER: "food_delivery"
      MYSQL_PASSWORD: "19e5a718a54a9fe0559dfbce6908"
      MYSQL_DATABASE: "food_delivery"
